// <auto-generated />
namespace ChatCoffee.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gidaychoi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gidaychoi));
        
        string IMigrationMetadata.Id
        {
            get { return "202303111616339_gidaychoi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
