<?xml version="1.0" encoding="utf-8"?><Database Name="ChatCoffeeDBContext" Class="MyDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-SJE0D3O4\SQLEXPRESS;Initial Catalog=ChatCoffeeDBContext;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ChatCoffeeDBContext" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ANH" Member="ANHs">
    <Type Name="ANH">
      <Column Name="MAANH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LINKANH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="MACF" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="COFFEE_ANH" Member="COFFEE" ThisKey="MACF" OtherKey="MACF" Type="COFFEE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.VANCHUYEN" Member="VANCHUYENs">
    <Type Name="VANCHUYEN">
      <Column Name="MAVT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENVT" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VANCHUYEN_HOADON" Member="HOADONs" ThisKey="MAVT" OtherKey="MAVT" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetRoles" Member="AspNetRoles">
    <Type Name="AspNetRole">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="RoleId" Type="AspNetUserRole" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserClaims" Member="AspNetUserClaims">
    <Type Name="AspNetUserClaim">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ClaimType" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserLogins" Member="AspNetUserLogins">
    <Type Name="AspNetUserLogin">
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUserRoles" Member="AspNetUserRoles">
    <Type Name="AspNetUserRole">
      <Column Name="UserId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="AspNetRole_AspNetUserRole" Member="AspNetRole" ThisKey="RoleId" OtherKey="Id" Type="AspNetRole" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUser" ThisKey="UserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ANH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="AspNetUser_AspNetUserClaim" Member="AspNetUserClaims" ThisKey="Id" OtherKey="UserId" Type="AspNetUserClaim" />
      <Association Name="AspNetUser_AspNetUserLogin" Member="AspNetUserLogins" ThisKey="Id" OtherKey="UserId" Type="AspNetUserLogin" />
      <Association Name="AspNetUser_AspNetUserRole" Member="AspNetUserRoles" ThisKey="Id" OtherKey="UserId" Type="AspNetUserRole" />
      <Association Name="AspNetUser_GIOHANG" Member="GIOHANGs" ThisKey="Id" OtherKey="Id" Type="GIOHANG" />
      <Association Name="AspNetUser_HOADON" Member="HOADONs" ThisKey="Id" OtherKey="Id" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.COFFEE" Member="COFFEEs">
    <Type Name="COFFEE">
      <Column Name="MACF" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENCF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KHOILUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XUATXU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="HSD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DANGCF" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MOTA" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="MALOAI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MATH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="COFFEE_ANH" Member="ANHs" ThisKey="MACF" OtherKey="MACF" Type="ANH" />
      <Association Name="COFFEE_CTDONHANG" Member="CTDONHANGs" ThisKey="MACF" OtherKey="MACF" Type="CTDONHANG" />
      <Association Name="COFFEE_CTGIOHANG" Member="CTGIOHANGs" ThisKey="MACF" OtherKey="MACF" Type="CTGIOHANG" />
      <Association Name="LOAISANPHAM_COFFEE" Member="LOAISANPHAM" ThisKey="MALOAI" OtherKey="MALOAI" Type="LOAISANPHAM" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="THUONGHIEU_COFFEE" Member="THUONGHIEU" ThisKey="MATH" OtherKey="MATH" Type="THUONGHIEU" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTDONHANG" Member="CTDONHANGs">
    <Type Name="CTDONHANG">
      <Column Name="MACF" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="COFFEE_CTDONHANG" Member="COFFEE" ThisKey="MACF" OtherKey="MACF" Type="COFFEE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="HOADON_CTDONHANG" Member="HOADON" ThisKey="MAHD" OtherKey="MAHD" Type="HOADON" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CTGIOHANG" Member="CTGIOHANGs">
    <Type Name="CTGIOHANG">
      <Column Name="MACF" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAGH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGGIA" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="COFFEE_CTGIOHANG" Member="COFFEE" ThisKey="MACF" OtherKey="MACF" Type="COFFEE" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="GIOHANG_CTGIOHANG" Member="GIOHANG" ThisKey="MAGH" OtherKey="MAGH" Type="GIOHANG" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIACHIs" Member="DIACHIs">
    <Type Name="DIACHI">
      <Column Name="MADC" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOHANG" Member="GIOHANGs">
    <Type Name="GIOHANG">
      <Column Name="MAGH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TONGTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TONGSL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TONGSP" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GIOHANG_CTGIOHANG" Member="CTGIOHANGs" ThisKey="MAGH" OtherKey="MAGH" Type="CTGIOHANG" />
      <Association Name="AspNetUser_GIOHANG" Member="AspNetUser" ThisKey="Id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="MAHD" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TONGDONGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="MAVT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MATT" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="HOADON_CTDONHANG" Member="CTDONHANGs" ThisKey="MAHD" OtherKey="MAHD" Type="CTDONHANG" />
      <Association Name="AspNetUser_HOADON" Member="AspNetUser" ThisKey="Id" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="VANCHUYEN_HOADON" Member="VANCHUYEN" ThisKey="MAVT" OtherKey="MAVT" Type="VANCHUYEN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="THANHTOAN_HOADON" Member="THANHTOAN" ThisKey="MATT" OtherKey="MATT" Type="THANHTOAN" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAISANPHAM" Member="LOAISANPHAMs">
    <Type Name="LOAISANPHAM">
      <Column Name="MALOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAISANPHAM_COFFEE" Member="COFFEEs" ThisKey="MALOAI" OtherKey="MALOAI" Type="COFFEE" />
    </Type>
  </Table>
  <Table Name="dbo.THANHTOAN" Member="THANHTOANs">
    <Type Name="THANHTOAN">
      <Column Name="MATT" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PHUONGTHUC" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="THANHTOAN_HOADON" Member="HOADONs" ThisKey="MATT" OtherKey="MATT" Type="HOADON" />
    </Type>
  </Table>
  <Table Name="dbo.THUONGHIEU" Member="THUONGHIEUs">
    <Type Name="THUONGHIEU">
      <Column Name="MATH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTH" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="THUONGHIEU_COFFEE" Member="COFFEEs" ThisKey="MATH" OtherKey="MATH" Type="COFFEE" />
    </Type>
  </Table>
</Database>